name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install client deps
        working-directory: client
        run: npm ci

      - name: Install server deps
        working-directory: server
        run: npm ci

      - name: Run client tests
        working-directory: client
        env:
          CI: true
        run: npm run test -- --run

      - name: Run server tests
        working-directory: server
        env:
          NODE_ENV: test
        run: npm run test
